# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

# image will be published to ghcr.io/<user>/<name>
name: uos-thinkpad-e14-gen-5
# description will be included in the image's metadata
description: This is my personal OS image for my lenovo thinkpad e14 gen 5.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination:
          / # copies files/system/* (* means everything inside it) into your image's root folder /
          # put configuration files you want in /usr/etc/ inside the image
          # while putting files in /etc/ is done on booted system by system administrators.
          # read more about this in files module reference.

  - type: fonts
    fonts:
      nerd-fonts:
        - Iosevka

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/antiderivative/libfprint-tod-goodix-0.0.9/repo/fedora-%OS_VERSION%/antiderivative-libfprint-tod-goodix-0.0.9-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/lazygit/repo/fedora-%OS_VERSION%/atim-lazygit-fedora-%OS_VERSION%.repo
    remove:
      - libfprint
    install:
      - libfprint-tod
      - libfprint-tod-goodix
      - bat
      - btop
      - eza
      - gh
      - jq
      - lazygit
      - neovim
      - ripgrep
      - starship
      - tldr
      - tmux
      - zsh
      - fortune-mod
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - zoxide
      - libevdev-devel

  - type: default-flatpaks
    configurations:
      - scope: system
        repo:
          title: Flathub (system)
        install:
          - org.gnome.gitlab.somas.Apostrophe
          - org.gnome.Snapshot
          - org.gnome.Evince
          - org.gnome.Loupe
          - org.gnome.Calculator
          - org.gnome.TextEditor
          - org.gnome.Weather
          - org.gnome.Calendar
          - com.github.tchx84.Flatseal
          - com.github.tenderowl.frog
          - com.spotify.Client
          - com.stremio.Stremio
          - nz.mega.MEGAsync
          - org.libreoffice.LibreOffice
          - org.mozilla.firefox
          - com.rtosta.zapzap
          - dev.zed.Zed
          - io.missioncenter.MissionCenter
          - app.zen_browser.zen

  # Install homebrew
  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry
    update-interval: "7d"

  - type: gnome-extensions
    install:
      - 3193 # Blur my shell
      # - 307 # Dash-to-Dock
      - 2980 # Internet Speed Meter
      - 5669 # Compact Top Bar
      - 4651 # Notification Banner Reloaded
      # - 5446 # Quick Settings Tweak
      
  - type: bling
    install:
      - dconf-update-service # a service unit that updates the dconf db on boot

  # Gnome customizations
  - type: files
    files:
      - source: dconf
        destination: /etc/dconf/db/local.d
      - source: evremap/usr
        destination: /usr/lib/systemd/system
      - source: evremap/bin
        destination: /usr/bin
      - source: evremap/etc
        destination: /etc

type: systemd
system:
  enabled:
    - evremap.service
    
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
