# image will be published to ghcr.io/<user>/<name>
name: uos-thinkpad-e14-gen-5
# description will be included in the image's metadata
description: This is my personal OS image for my lenovo thinkpad e14 gen 5.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
                       # put configuration files you want in /usr/etc/ inside the image
                       # while putting files in /etc/ is done on booted system by system administrators.
                       # read more about this in files module reference.

  - type: fonts
    fonts:
      nerd-fonts:
        - Iosevka
  
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/antiderivative/libfprint-tod-goodix-0.0.9/repo/fedora-%OS_VERSION%/antiderivative-libfprint-tod-goodix-0.0.9-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/lazygit/repo/fedora-%OS_VERSION%/atim-lazygit-fedora-%OS_VERSION%.repo
    remove:
      - libfprint
    install:
      - libfprint-tod
      - libfprint-tod-goodix
      - autojump
      - bat
      - btop
      - eza
      - gh
      - jq
      - lazygit
      - neovim
      - ripgrep
      - starship
      - tldr
      - tmux
      - zsh
      - fortune-mod
      - zsh-autosuggestions
      - zoxide


  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - com.github.tchx84.Flatseal
        - com.github.tenderowl.frog
        - com.spotify.Client
        - com.stremio.Stremio
        - nz.mega.MEGAsync
        - org.gnome.gitlab.somas.Apostrophe
        - org.libreoffice.LibreOffice
        - org.mozilla.firefox
        - com.rtosta.zapzap
        - dev.zed.Zed
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  # Install homebrew
  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry
    update-interval: ['7d', '0h', '0m']
    
  - type: gnome-extensions
    install:
      - 3193 # Blur my shell
      - 307 # Dash-to-Dock
      - 2980 # Internet Speed Meter
      - 5669 # Compact Top Bar
      - 4651 # Notification Banner Reloaded
      - 5446 # Quick Settings Tweak

  - type: files
    files:
      - source: dconf
        destination: /etc/dconf/db/local.d

  - type: bling
    install:
      - dconf-update-service # a service unit that updates the dconf db on boot

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
